- hosts: 192.168.1.17
  become: true
 
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

    - name: Upgrade all packages
      become: true
      apt: 
	upgrade=dist
        force_apt_get=yes

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
